# netlify.toml
# [build.environment]
#   NODE_VERSION = "12.22.7"

[functions]
  directory = "functions"
  included_files = ["node_modules/shopify-api-node/mixins/**"]
  external_node_modules = ["lodash/assign"]
