# netlify.toml
# [build.environment]
#   NODE_VERSION = "12.22.7"

[functions]
  node_bundler = "esbuild"
  directory = "functions"
  included_files = ["shopify-api-node"]
  external_node_modules = ["lodash"]
